pipeline {
    agent any
    environment {
        AWS_ACCOUNT_ID = credentials('account_id')
        AWS_DEFAULT_REGION="us-east-1"     
    }
        
    stages {
        stage('Infrastructure Deployment') {
           environment { 
             AWS_ACCESS_KEY_ID = credentials('aws_access_key_id')
             AWS_SECRET_ACCESS_KEY = credentials('aws_secret_access_key')
           }
           steps {
              script {
                  sh "cd MAINinfra && terraform init"
                  sh "cd MAINinfra && terraform validate"
                  sh "cd MAINinfra && terraform plan"
                  sh "cd MAINinfra && terraform ${action} --auto-approve"
            }
        }
               
     }
    }
    
}
