pipeline {
    agent any
    environment {
        AWS_ACCOUNT_ID = credentials('ACCOUNTID')
        AWS_DEFAULT_REGION="us-east-1"     
    }
        
    stages {
        stage('Infrastructure Deployment') {
           environment {
             AWS_PROFILE= credentials('Profile')  
             AWS_ACCESS_KEY_ID = credentials('ACCESSkey')
             AWS_SECRET_ACCESS_KEY = credentials('SECRETkey')
           }
           steps {
              script {
                  sh "cd MAINinfra && terraform init"
                  sh "cd MAINinfra && terraform validate"
                  sh "cd MAINinfra && terraform plan"
                  sh "cd MAINinfra && terraform ${action} --auto-approve"
            }
        }
               
     }
    }
    
}
